[package]
name = "borrowing"
version = "0.1.0"
authors = ["bxq2011hust <bxq2011hust@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
